
stages:
    - publish
    - deploy
    # - mergetostg
publish:
    variables:
        TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:cypress_latest
        TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
    image: docker:latest
    stage: publish
    services:
        - docker:dind
    script:
        # - cp $env_dev .env
        - docker build -t $TAG_LATEST .
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
        - docker push $TAG_LATEST
        - docker system prune -a -f
    only:
        - dev
deploy:
    image: alpine:latest
    stage: deploy
    before_script:
        - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
        - eval $(ssh-agent -s)
        - echo "$PRIV_KEY_DEPLOY_NEW" | tr -d '\r' | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
    script:
        - ssh -o StrictHostKeyChecking=no $SSH_USER_DEPLOY@$VM_IP_DEPLOY_NEW "/usr/local/bin/kubectl rollout restart deployment/cypress-deploy"
    only:
        - dev